defaults:
  - _self_
  - foundation: resnet34
  - flood: unet_siamese

hydra:
  run:
    dir: ${oc.env:GSN_SN8_DIR}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

# aoi = area of interest
aoi_dirs:
  - 'Germany_Training_Public'
  - 'Louisiana-East_Training_Public'

output_dir: ${hydra:runtime.output_dir}
output_csv_basename: 'sn8_data'
val_percent: '0.15'