name: gsn-sn8
channels:
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch
  - pytorch-lightning
  - torchvision
  - pytorch-cuda=12.1
  - scikit-image
  - fiona
  - shapely
  - geojson
  - utm
  - osmnx
  - statsmodels
  - geopandas
  - jupyter
  - plotly
  - matplotlib
  - segmentation-models-pytorch
  - jsonschema==4.22.0
  - neptune==1.10.4
  - pip:
      - opencv-python
      - hydra-core
      - opencv-contrib-python==4.10.0.84
      - albumentations #==1.4.8