name: gsn-sn8
channels:
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch
  - pytorch-lightning
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-image
  - fiona
  - shapely
  - geojson
  - utm
  - osmnx
  - statsmodels
  - geopandas
  - jupyter
  - plotly
  - matplotlib
  - segmentation-models-pytorch
  - pip:
      - opencv-python
      - hydra-core